export const ActionTypes={
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    A_to_Z:'az',
    Z_to_A:'za',
}
