export const DefaultConstants = {   
// FeatureSection-constants
QUALITYPRODUCT:'Quality Product',
FREESHIPPING:'Free Shipping',
RETURNPOLICY:'14-Day Return',
SUPPORT:'24/7 Support',


// productsSection-constants
FIFTEENPRODUCTS:'15 Products',

//shopingcart-constants
CARTSUMMARY:'Cart Summary',
EMPTYCART:'Your cart is empty go to shop page and add items',
SUBTOTAL:'Subtotal',
SHIPPING:'Shipping',
FREE:'Free',
TOTAL:"Total",
PROCEEDTOCHECKOUT:'Proceed To Checkout',
 SHOPPINGCART:'SHOPPING CART',
 SHOPPINGCARTSMALL:'Shopping cart',

    //TopNavbar constants
     FAQ:"FAQs",
     HELP:"Help",
     SUPPORTS:"Support",
     E:"E",
     SHOPPER:"Shopper",

     //MainNavbar constants
     MENSDRESSES:"Men's Dresses",
     WOMENSDRESSES:"Women's Dresses",
     BABAYSDRESSES:"Baby's Dresses",
     SHIRTS:"Shirts",
     JEANS:"Jeans",
     SWIMWEAR:"Swimwear",
     SLEEPWEAR:"Sleepwear",
     SPORTSWEAR:"Sportswear",
     JUMPSUITS:"Jumpsuits",
     BLAZERS:"Blazers",
     JACKETS:"Jackets",
     SHOES:"Shoes",
     CATEGORIES:"Categories",
     DRESSES:"Dresses",
     HOME:"Home",
     SHOP:"Shop",
     SHOPDETAIL:"Shop Detail",
     PAGES:"Pages",
     CHECKOUT:"Checkout",
     CONTACT:"Contact",
     LOGOUT:"Logout",
     LOGIN:"Login",
     REGISTER:"Register",
     SHOPNOW:"",
     FASHIONABLEDRESS:"Fashionable Dress",
     REASONABLEPRICE:"Reasonable Price",
     TENOFFYOURFIRSTORDER:"10% Off Your First Order",

     //shopdetailpage constants
     DESCRIPTION:"Description",
     INFORMATION:"Information",
     REVIEWS:"Reviews",
     PRODUCTDESCRIPTION:"Product Description",
     ADDITIONALINFORMATION:"Additional Information",
     LEAVEREVIEW:"Leave a review",
     YOURRATING:"Your Rating * :",
     YOURREVIEW:"Your Review *",
     YOURNAME:"Your Name *",
     YOUREMAIL:"Your Email *",
     LEAVEYOURREVIEW:"Leave Your Review",
     YOUMAYALSOLIKE:"You May Also Like",
     XS:"XS",
     S:"S",
     L:"L",
     M:"M",
     XL:"XL",
     BLACK:"Black",
     WHITE:"White",
     RED:"Red",
     BLUE:"Blue",
     GREEN:"Green"
}
