export const DefaultConstants = {
    //TopNavbar constants
     FAQ:"FAQs",
     HELP:"Help",
     SUPPORT:"Support",
     E:"E",
     SHOPPER:"Shopper",

     //MainNavbar constants
     MENSDRESSES:"Men's Dresses",
     WOMENSDRESSES:"Women's Dresses",
     BABAYSDRESSES:"Baby's Dresses",
     SHIRTS:"Shirts",
     JEANS:"Jeans",
     SWIMWEAR:"Swimwear",
     SLEEPWEAR:"Sleepwear",
     SPORTSWEAR:"Sportswear",
     JUMPSUITS:"Jumpsuits",
     BLAZERS:"Blazers",
     JACKETS:"Jackets",
     SHOES:"Shoes",
     CATEGORIES:"Categories",
     Home:"Home",
     SHOP:"Shop",
     SHOPDETAIL:"Shop Detail",
     PAGES:"Pages",
     SHOPPINGCART:"Shopping Cart",
     CHECKOUT:"Checkout",
     CONTACTUS:"Contact Us",
     LOGOUT:"Logout",
     LOGIN:"Login",
     REGISTER:"Register",
     SHOPNOW:"",
     FASHIONABLEDRESS:"Fashionable Dress",
     REASONABLEPRICE:"Reasonable Price",
     TENOFFYOURFIRSTORDER:"10% Off Your First Order",

     //shopdetailpage constants
     DESCRIPTION:"Description",
     INFORMATION:"Information",
     REVIEWS:"Reviews",
     PRODUCTDESCRIPTION:"Product Description",
     ADDITIONALINFORMATION:"Additional Information",
     LEAVEREVIEW:"Leave a review",
     YOURRATING:"Your Rating * :",
     YOURREVIEW:"Your Review *",
     YOURNAME:"Your Name *",
     YOUREMAIL:"Your Email *",
     LEAVEYOURREVIEW:"Leave Your Review",
     YOUMAYALSOLIKE:"You May Also Like",
     XS:"XS",
     S:"S",
     L:"L",
     M:"M",
     XL:"XL",
     BLACK:"Black",
     WHITE:"White",
     RED:"Red",
     BLUE:"Blue",
     GREEN:"Green"
}